### ISSUE TITLE
Pelican 3.6.3 Tags in sidebar does not display

### ISSUE THREAD

**Issue by ecsys** [robulouski/voidy-bootstrap#10]
Hi, I tried to use this template for my blog. Thanks for sharing this beautiful theme.

I noticed that with Pelican 3.6.3 the Tags in the sidebar does not display and I fixed it by changing the **tag_cloud** to **tags** in line 50 in templates/includes/sidebar.html.

I just think it might be good to let you know this issue.

**Comment by robulouski** [comment]
Thanks for letting me know!

Yes, this appears to be an issue caused by tag cloud support being removed from Pelican itself in version 3.6 and moved to a plugin instead.

As such, I'm inclined to remove the tag cloud by default in the theme, and provide a way to optionally enable it for those that want to configure the tag_cloud plugin.

While changing `tag_cloud` to `tags` does fix the immediate problem of the tag cloud not displaying anything, the styling is still broken, so the result is more of a "tag list" than a "tag cloud".
