### ISSUE TITLE
Enhancement proposal

### ISSUE THREAD

**Issue by ssteinerx** [robulouski/voidy-bootstrap#13]
I'm loving voidy-bootstrap; just what I needed to get over the proverbial hump while converting a blog to Pelican.

One thing I'm having difficulty with is figuring out which setting/template is injecting which piece of resultant html.  Also, it's difficult to style individual content hunks e.g. the article_header if I move them around at all since there is no enclosing wrapper.

I would propose to add a `<div>` surrounding each template's content and, adding a placeholder `<div>` surrounding each `include` in each template to make it very easy to find the corresponding HTML code (in the `.html` files or at runtime).

This is already done in e.g. `taglist.html` where there is a `<div class="article-tag-list">` though I might argue that the class name should simply be `taglist` to correspond to the actual template name.

NOTE: The major parts (e.g. `#sidebar`) already have an `id` defined.

This should be completely backwards compatible as it is only adding `<div>` wrappers and classes that (most likely) didn't exist before.

I'd be happy to do the work and submit a pull request if you agree with this idea.

**Comment by robulouski** [comment]
I'm not sure about this idea, although I'm not entirely sure I understand what problem this is intended to solve.  While I guess it probably wouldn't matter too much either way, not sure how adding more DIV markup would be helpful.  Especially since the theme goes to great lengths to allow users to insert their own arbitrary bits of HTML.

You do realise you can replace the contents of `article_header.html` using the `CUSTOM_ARTICLE_HEADERS` and/or `CUSTOM_INDEX_ARTICLE_HEADERS` settings (and thereby override article_header with your own content)?

Note that `article_header.html` is a bit unusual for a number of reasons.  It provides a "default" article header content implementation, which can be overridden with the above settings.  Also, it's included by both `index.html` and  `article.html`, and has subtly different semantics in both.  When included from `article.html` it's  enclosed by a `<header>` block with a class name of "article-header".  I believe a `header` wouldn't be semantically appropriate in index pages, so it's omitted.  This is probably why I didn't originally include a wrapper DIV inside `article-header.html` -- because it's intended as one minimal default implementation to satisfy all the above points.  Personally, I never use `article-header.html` in practice anyway, because I strongly feel blog articles should have different headers on article pages and index pages, so I always provide my own implementations of both. (i.e. I *always* use `CUSTOM_ARTICLE_HEADERS` and `CUSTOM_INDEX_ARTICLE_HEADERS` and provide different templates for both.)

I certainly don't think indiscriminately adding placeholder DIV wrappers around *every* include is worth doing, and might even be problematic.  While it might not necessarily cause backward compatibility issues, it would reduce flexibility.  Some of the "Custom Includes" settings accept lists to allow additional content to be composed with multiple template fragments -- even multiple templates consisting of *inline* elements.  (Although admittedly this is an unlikely use case, but still...)  Wrapping each include directive with a DIV imposes block positioning and therefore removes the option of composing custom content using inline (i.e. SPAN) elements (without additional CSS for positioning), so I feel this would reduce flexibility without really adding much of value.

Which leads to a broader point that all the template fragments in the "includes" subdirectory are essentially starting points rather than full featured implementations -- use them if it makes sense for your site, but the theme is designed so that (hopefully) everything there can be replaced with custom templates tailored as required.

However, if yourself (or anyone else out there) would like to weigh in with examples of specific pain points with the theme that adding more markup would solve, I'd be happy to reconsider, but at this stage I'd rather keep things as minimal as practical.

As for the class names, I'm generally unhappy with the somewhat haphazard and inconsistent naming of classes throughout the theme.  I do wish I'd given more thought to some sort of consistent naming convention from the start, when I first created the theme (I have a preference for longer, prefixy class names, so if anything, I'd argue the filename of `taglist.html` should be changed to match the class name, rather than the other way round).  However, it's intended as a fairly minimal theme, so I'm not sure how much of a problem this is in practice.  I'm (perhaps wrongly) assuming most people who care about class names would be adding their own templates via the "custom includes" settings, along with their own class names.
